name: Setup pnpm
description: "This is a composite GitHub Action that sets up pnpm, node and installs the project's dependencies."
inputs:
  node-version:
    description: "Node.js version"
    required: true
runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@v2
      with:
        version: 8.5.1
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        cache: pnpm
    - run: pnpm install --frozen-lockfile
      shell: bash
